### ISSUE TITLE
Update `Bit.TodoTemplate` based on recent dotnet maui blazor template changes

### ISSUE THREAD

**Issue by ysmoradi** [bitfoundation/bitplatform#2434]

**Comment by ysmoradi** [comment]
Need review: @msynk 

```css
.status-bar-safe-area {
    display: none;
}

@supports (-webkit-touch-callout: none) {
    .status-bar-safe-area {
        display: flex;
        position: sticky;
        top: 0;
        height: env(safe-area-inset-top);
        background-color: #f7f7f7;
        width: 100%;
        z-index: 1;
    }

    .flex-column, .navbar-brand {
        padding-left: env(safe-area-inset-left);
    }
}
```

```html
<FocusOnNavigate RouteData="@routeData" Selector="h1" />
```

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover" />
```
