### ISSUE TITLE
Collecting all animations in SCSS

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [bitfoundation/bitplatform#4091]
Collecting all animations in SCSS and preventing them from repeating in the rest of the SCSS files in each component. ex. 
```scss
@keyframes opacity {
    0% {
        opacity: 0;
    }

    100% {
        opacity: 1;
    }
}
```
