### ISSUE TITLE
RightToLeft Direction in BitCarousel causing display issues

### ISSUE THREAD

**Issue by hootanht** [bitfoundation/bitplatform#6679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**GitHub Issue for BitPlatform: RightToLeft Direction in BitCarousel causing display issues**

**Issue Description:**
When using the RightToLeft Direction in BitCarousel, the carousel breaks, and the last image covers the section. Additionally, when the image changes, it goes under the image that was previously displayed. Removing the RightToLeft Direction resolves the issue.

**Code Snippet:**
```html
<BitCarousel InfiniteScrolling="true" Direction="BitDirection.RightToLeft" Style="@(MustShoeImage? "width: 100%;height: 211px;" : "display:none")">
    @foreach (var image in Images)
    {
        <BitCarouselItem>
            <img class="image set-max-width carouselItem-image" src="@image" @onload="HandleImageOnLoaded" @onerror="HandleVehicleMarkerImageError" />
        </BitCarouselItem>
    }
</BitCarousel>
```

**Environment:**
- BitPlatform Template Version: v-8.7.1
- Browser/Device: Chrome-Android , Safari-IOS , Edge-Windows

**Screenshots/Additional Information:**

https://github.com/bitfoundation/bitplatform/assets/27281206/36731e12-1715-4147-8a67-4ea930d0d4f5

**Note:**
Please prioritize fixing this issue as it affects the live product. Keep us informed about the progress and resolution. Thank you!

### Expected Behavior

The BitCarousel should function correctly when using the RightToLeft Direction, and images should display without covering the section or going under the previously shown image.

### Steps To Reproduce

1. Use the provided code snippet with RightToLeft Direction in BitCarousel.
2. Observe the carousel breaking and the last image covering the section.
3. Notice that when the image changes, it goes under the previously displayed image.

### .NET Version

8.0.100

### Anything else?

**Additional Information:**
- Issue is impacting the live product.
- The issue does not occur when the RightToLeft Direction is not used.

Hope this video helps :

https://github.com/bitfoundation/bitplatform/assets/27281206/d95db681-1128-4907-8113-df09959d543f

**Comment by msynk** [comment]
@hootanht I believe there is something in your custom CSS styles that conflicts with the CarouselItem style that creates this issue since the RTL sample in the Carousel demo page works fine.
Could you please share the source code so we can check the problem?

**Comment by hootanht** [comment]
Sure, here is the custom CSS : 

```scss
.carousel-wrapper {
    ::deep .bit-icon--ChevronRight {
        background: url("./images/icons/chevron-right.svg") center/cover
            no-repeat !important;
        color: transparent !important;
    }

    ::deep .bit-icon--ChevronLeft {
        background: url("./images/icons/chevron-left.svg") center/cover
            no-repeat !important;
        color: transparent !important;
    }

    ::deep .bit-csl-rbt {
        outline: 0;
        opacity: 1 !important;
        text-decoration: none;
        color: var(--bit-clr-act-hover-fg-pri);
    }

    ::deep .bit-csl-lbt {
        outline: 0;
        opacity: 1 !important;
        text-decoration: none;
        color: var(--bit-clr-act-hover-fg-pri);
    }

    ::deep .bit-csl-dot .current {
        background-color: $primary-sky-night !important;
        width: 10px !important;
        height: 10px !important;
    }

    ::deep .bit-csl-dot {
        display: flex !important;
        justify-content: center !important;
        align-items: center !important;
    }

    ::deep .bit-csl-dot div {
        border-radius: 50% !important;
        width: 7px !important;
        height: 7px !important;
        display: inline-block;
        margin-right: 5px !important;
        margin-left: 0px !important;
        background-color: $primary-soap !important;
    }
}

.carouselItem-image {
    height: 200px;
    display: block;
    margin: auto;
}
```
